services:
  - type: web
    name: django-app
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn QAPortal.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "django-app-x838.onrender.com"
    plan: free

databases:
  - name: django-db
    plan: free
